### ISSUE TITLE
ThermoFisher.CommonCore NuGet packages provided by Thermo Fisher Scientific

### ISSUE THREAD

**Issue by tobiasko** [PNNL-Comp-Mass-Spec/Thermo-Raw-File-Reader#2]
Hi PNNL comp MS,

we just realised that the RawFileReader homepage is offline (most likely due to a complete remake of planet orbitrap web pages). Are you aware of any changes regarding how Thermo plans to distribute the CommonCore .NET assembly?

Greetings,
Tobi

**Comment by zmunro** [comment]
Is there any documentation anywhere on this library now that the homepage is offline?

**Comment by FarmGeek4Life** [comment]
The last information we had, when we noticed that PlanetOrbitrap was redirecting to "AnalyteGuru", with a completely different look, was that the change also caught those in charge of RawFileReader at Thermo off-guard, and they were looking at how they could re-establish a site for it. With a quick web search, I did see that they at least have the slides from the 2019 ASMS presentation for RawFileReader available on AnalyteGuru, and the instructions for getting access to RawFileReader are on the 3rd-from-last slide (contact Jim Shofstahl via email, address is in the PDF available on the site):
https://www.analyteguru.com/t5/Scientific-Library/Raw-File-Reader/ta-p/8870

The documentation for RawFileReader is still available via the OneDrive share, but apparently OneDrive removes access to the share after a certain amount of time, so if you previously had access to that OneDrive share and no longer do, then you need to contact Jim Shofstahl to resolve the issue.
